[build]
builder = "dockerfile"

[deploy]
startCommand = "./bin/rails db:prepare && HTTP_PORT=${PORT:-3000} bundle exec thrust ./bin/rails server"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
